name: "Bug 🐞"
description: "File a bug/ issue"
title: "Bug: "
labels: ["bug", "triage"]
projects: ["@dwarrenicon's Product Board", ]
assignees:
  - dwarrenicon
body:
  - type: markdown
    attributes:
      value: "Please fill out this bug report!" 

  - type: textarea
    id: describe
    attributes:
      label: Describe the bug. 
      description: "A clear and concise description of what the bug is."
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description:  "Steps to reproduce the behavior:"
      placeholder: 1. Go to... 2. Click on... 3. Scroll down to... 4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: Tell us what was meant to happen.
    validations:
      
      
  - type: dropdown
    id: portal
    attributes:
      label: Portal
      description: "What portal are you running?"
      options:
        - Individual
        - Employer
        - Admin
      
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: "What environment are you seeing the problem in?"
      options:
        - Localhost
        - Staging
        - Pre-Prod
        - Prod
        
  - type: textarea
    id: logs
    attributes:
      label: Please include any relevant screenshots or log output
      description: "Please copy and paste any relevant, screenshots, error messages, code snippets or log output. This will be automatically formatted into code, so no need for backticks."
      render: shell

      

